Specify bucket name and allow other partitions
rhythmictech/terraform-cloudtrail-bucket pull request #5
Opened 2020-07-24 13:58 UTC by fdamstra

Thanks for the modules.

I made two minor improvements:
* ARNs are now built with the current partition, which allows this to work in GovCloud, and likely China, too.
* You can now specify the bucket name. The default name (`{account_id}-{region}-cloudtrail`) was both predictable and didn't make a lot of sense for me with cross-account logging.

Neither change breaks backward compatibility.

2020-07-24 19:36 UTC, cdaniluk requested changes
Appreciate the PR. We've been moving a lot of our modules over to make `bucket_name` more flexible but hadn't done this one yet.

2020-07-24 19:36 UTC, cdaniluk commented on main.tf
> +  bucket_name = var.bucket_name == "" ? "${local.account_id}-${var.region}-cloudtrail" : var.bucket_name
```suggestion
  bucket_name = var.bucket_name == null ? "${local.account_id}-${var.region}-cloudtrail" : var.bucket_name
```

2020-07-24 19:36 UTC, cdaniluk commented on variables.tf
> +  default     = "" # can't dynamically build the bucket name here
```suggestion
  default     = null
```

2020-07-24 19:36 UTC, cdaniluk commented on main.tf
> +  bucket_name = var.bucket_name == "" ? "${local.account_id}-${var.region}-cloudtrail" : var.bucket_name
this would ideally come above `partition` to keep args sorted

2020-07-25 12:28 UTC, fdamstra commented
Changes incorporated, @cdaniluk

2020-08-05 22:44 UTC, sblack4 approved these changes
:shipit:

2020-08-05 22:44 UTC, merged